# basic options
title: </> Sachin Thakur
author: Sachin Thakur
description: A wonderful site
github_username:  SachThakur
linkedin_username: sachin-thakur-376534216

# Build settings
markdown: kramdown
theme: minima
