# basic options
title: Your awesome title
author: Sachin Thakur
description: A wonderful site
github_username:  SachThakur
linkedin_username: sachin-thakur-376534216

# Build settings
markdown: kramdown
theme: minima
